# Font
font_family JetBrains Mono
font_size 12.0

# Colors - black and white theme
background #000000
foreground #ffffff
cursor #ffffff
cursor_text_color #000000
selection_background #ffffff
selection_foreground #000000
url_color #6e6eff

# Black
color0  #000000
color8  #555555

# White
color7  #ffffff
color15 #ff0000

# Red
color1  #9c9c9c
color9  #ff6e6e

# Green
color2  #44aa44
color10 #69ff94

# Yellow
color3  #aaaa22
color11 #ffffa5

# Blue
color4  #000000
color12 #6e6eff

# Magenta
color5  #aa44aa
color13 #ff92df

# Cyan
color6  #6d6d6d
color14 #a4ffff

# Transparency
background_opacity 0.8

# Window
window_padding_width 10
hide_window_decorations yes
nano ~/.config/kitty/kitty.conf
